In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [ ]:
data = pd.read_csv("DATA_2B.csv")
data

seating_capacity  year_of_manufacture  price. Price  B0  log(seating)  \
0                    2                 2022           249   1      0.301030   
1                    7                 2022          4286   1      0.845098   
2                    8                 2023           885   1      0.903090   
3                    5                 2023           754   1      0.698970   
4                    8                 2022           850   1      0.903090   
...                ...                  ...           ...  ..           ...   
4995                 5                 2011           325   1      0.698970   
4996                 5                 2023          1319   1      0.698970   
4997                 5                 2018           545   1      0.698970   
4998                 5                 2022           689   1      0.698970   
4999                 5                 2019           398   1      0.698970   

      log(year)  
0      3.305781  
1      3.305781  
2      3.305996  
3      3.305996  
4      3.305781  
...         ...  
4995   3.303412  
4996   3.305996  
4997   3.304921  
4998   3.305781  
4999   3.305136  

[5000 rows x 6 columns]

In [ ]:
x = np.array(data[['log(seating)', 'log(year)']]).reshape((-1, 2))
y = np.array(data['price. Price']).reshape((-1, 1))
x, y

(array([[0.30103   , 3.30578115],
        [0.84509804, 3.30578115],
        [0.90308999, 3.30599588],
        ...,
        [0.69897   , 3.30492116],
        [0.69897   , 3.30578115],
        [0.69897   , 3.30513632]]),
 array([[ 249],
        [4286],
        [ 885],
        ...,
        [ 545],
        [ 689],
        [ 398]]))

In [ ]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [ ]:
reg.intercept_

-768239.0724136992

In [ ]:
reg.coef_

array([     0.        ,  -3078.03933329, 233608.26065767])

In [ ]:
reg.score(x,y)

0.020160139734869187

In [ ]:

y = data['price. Price']

# For independent variables (x), select the desired columns
x = data[['log(seating)', 'log(year)']]

# Add a constant term to the independent variables
x = sm.add_constant(x)

reg = sm.OLS(y,x).fit()
reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:           price. Price   R-squared:                       0.020
Model:                            OLS   Adj. R-squared:                  0.020
Method:                 Least Squares   F-statistic:                     51.41
Date:                Sun, 07 Apr 2024   Prob (F-statistic):           7.96e-23
Time:                        09:38:12   Log-Likelihood:                -46566.
No. Observations:                5000   AIC:                         9.314e+04
Df Residuals:                    4997   BIC:                         9.316e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const        -7.682e+05   1.25e+05     -6.131      0.000   -1.01e+06   -5.23e+05
log(seating) -3078.0393    367.662     -8.372      0.000   -3798.818   -2357.261
log(year)     2.336e+05   3.79e+04      6.161      0.000    1.59e+05    3.08e+05
==============================================================================
Omnibus:                     5614.000   Durbin-Watson:                   1.660
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           605360.083
Skew:                           5.729   Prob(JB):                         0.00
Kurtosis:                      55.673   Cond. No.                     1.22e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.22e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""